import { Song } from './Song';

export const categories = {
  jazz: [
    new Song(
      'Miles Davis',
      'So What',
      4,
      19,
      5,
      'https://i.ytimg.com/vi/ylXk1LBvIqU/maxresdefault.jpg',
    ),
    new Song(
      'John Coltrane',
      'My Favorite Things',
      6,
      20,
      10,
      'https://upload.wikimedia.org/wikipedia/en/9/9b/My_Favorite_Things.jpg',
    ),
    new Song(
      'Dave Brubeck',
      'Take Five',
      4,
      1,
      5,
      'https://m.media-amazon.com/images/I/71lsG3fCaOL._SL1200_.jpg',
    ),
    new Song(
      'John Coltrane',
      'Acknowledgement',
      5,
      20,
      4,
      'https://cdn.allsolos.com/images/album/67.jpg',
    ),
    new Song(
      'Weather Report',
      'Birdland',
      3,
      2,
      7,
      'https://m.media-amazon.com/images/I/81mOS7+WMtL._SS500_.jpg',
    ),
    new Song(
      'Pharoah Sanders',
      'The Creator Has a Master Plan',
      4,
      50,
      8,
      'https://cdns-images.dzcdn.net/images/cover/08e2f6ab86a4e20100a0dccc76c35d28/500x500.jpg',
    ),
  ],
  rock: [
    new Song(
      'Led Zeppelin',
      'Whole Lotta Love',
      3,
      20,
      8,
      'https://i.discogs.com/32RD2WkZcDjwe4FpuMfDw1-8QW8Ea3us90yNsEHK9Dc/rs:fit/g:sm/q:90/h:600/w:593/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTE4MTAw/NDUtMTM3NzYyNjY1/MS04NjYwLmpwZWc.jpeg',
    ),
    new Song(
      'Jimi Hendrix',
      'Purple Haze',
      4,
      17,
      6,
      'https://i1.sndcdn.com/artworks-000162911409-92b4lx-t500x500.jpg',
    ),
    new Song(
      'The Rolling Stones',
      'Sympathy for the Devil',
      5,
      1,
      9,
      'https://upload.wikimedia.org/wikipedia/en/thumb/0/0d/Rolling_Stones_Sympathy_for_the_Devil.jpg/220px-Rolling_Stones_Sympathy_for_the_Devil.jpg',
    ),
    new Song(
      'Queen & David Bowie',
      'Under Pressure',
      3,
      19,
      12,
      'https://m.media-amazon.com/images/M/MV5BOGMzZWNhNjktZmU5MC00ZDdlLTg2ZDItMTQ4NmExNjJiNDM2XkEyXkFqcGdeQXVyNDQ5MDYzMTk@._V1_FMjpg_UX1000_.jpg',
    ),
    new Song(
      'Pink Floyd',
      'Comfortably Numb',
      3,
      22,
      11,
      'https://i.pinimg.com/originals/77/50/c2/7750c2c844f3442b61c0b2da04e44766.png',
    ),
  ],
  country: [
    new Song(
      'Johnny Cash',
      'I Walk the Line',
      2,
      30,
      9,
      'https://i.discogs.com/u5iOE02JpeR9Hsnq96umlWnxwOO4IOMyAzqqZbVoaLI/rs:fit/g:sm/q:40/h:300/w:300/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTExMDkz/MTUtMTI2NzgwNTk5/OS5qcGVn.jpeg',
    ),
    new Song(
      'Johnny Cash and June Carter',
      'Jackson',
      3,
      13,
      7,
      'https://images-na.ssl-images-amazon.com/images/I/61gFZ-a88IL._SY445_SX342_QL70_ML2_.jpg',
    ),
    new Song(
      'Garth Brooks',
      'The Dance',
      4,
      22,
      5,
      'https://i.scdn.co/image/ab67616d0000b2733480d5fc1a12593de2567c62',
    ),
    new Song(
      'John Denver',
      'Take Me Home, Country Roads',
      3,
      22,
      4,
      'https://i.scdn.co/image/ab67616d0000b27334fb2b0117a542d515dc78d6',
    ),
    new Song(
      'Glen Campbell',
      'Rhinestone Cowboy',
      4,
      3,
      7,
      'https://d8mkdcmng3.imgix.net/8ffd/music-audio-cds-country-glen-campbell-glen-campbell-rhinestone-cowboy-cd.jpg?auto=format&bg=0FFF&fit=fill&h=600&q=100&w=600&s=04dbcadd2908ff579e50a9fba89feab8',
    ),
  ],
  pop: [
    new Song(
      'Beyoncé',
      'Single Ladies (Put a Ring on It)',
      3,
      33,
      5,
      'https://upload.wikimedia.org/wikipedia/en/4/44/Single_Ladies_%28Put_a_Ring_on_It%29_cover.png',
    ),
    new Song(
      'Rihanna feat. Jay-Z',
      'Umbrella',
      3,
      12,
      7,
      'https://upload.wikimedia.org/wikipedia/en/0/01/Rihanna_-_Umbrella.png',
    ),
    new Song(
      'Taylor Swift',
      'Shake it Off',
      4,
      2,
      4,
      'https://note-store.com/upload/iblock/c5b/Taylor-Swift-_-Shake-It-Off.jpg',
    ),
    new Song(
      'Britney Spears',
      'Toxic',
      3,
      14,
      6,
      'https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Britney_Spears_Toxic.png/220px-Britney_Spears_Toxic.png',
    ),
    new Song(
      'Adele',
      'Rolling in the Deep',
      4,
      12,
      8,
      'https://i1.sndcdn.com/artworks-000129765513-hy7dyr-t500x500.jpg',
    ),
  ],
};
